version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: nginx-compose
    image: nginx
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - ./conf:/etc/nginx/conf.d
     # - logvolume01:/var/log
  redis:
    container_name: redis-compose
    image: redis
